### PR TITLE
Azure allow use of existing vnet

### PR DESCRIPTION
**Pull request by ajrpayne**
We had a use case where the aks cluster needed to be attached to an existing vnet, instead of creating a new vnet.

This pull request allows setting the subnet as part of a existing vnet. Defaults to creating a new vnet if the variables aren't set, matching previously behavior.

### CODE REVIEW

**Comment by pst** [comment]
Supporting existing networks (VPC/Vnet) is not something I want to support. This has come up a few times and I think it's better to have the modules have everything that clusters need included.

I believe this will allow me to provide higher quality long-term, because it's easier for me to test and also allows me to unify between cloud providers as much as possible. To integrate with other cloud services I use the peering or endpoint features the providers have.

I certainly would like to hear your thoughts and if you have strong arguments that I may be missing here I can change my opinion. But if I accept it for one provider, I would also have to do it for the two others. So it would definitely be a bigger project to get this merged.

**Comment by ajrpayne** [comment]
I tried this with azure's networking peering feature. When on the same vnet the DNS entries of the VMs we needed to reached were auto populated by Azure. If there is a quick and easy way to have Azure auto populate the DNS entries from the peered vnet we could live without this feature.

**Comment by jeacott1** [comment]
+1 - I need to be able to create aks clusters that can attach to existing vnet infrastructure.

**Comment by pst** [comment]
I'm closing this, because:

- I don't see strong arguments or many user requests to do it
- The amount of work required to do this for all three providers is not justified given the limited value the change provides
- Nobody has stepped up to do the work

I understand you're maintaining your own fork for AKS and that's fine for me. I suppose for anyone looking for AKS only and existing VNet, they can just use your fork aswell.

**Pull request closed without merging**
