### PR TITLE
Feature digital ocean

### PR DESCRIPTION
**Pull request by Spazzy757**
# Changelog

- Adds integration with Digital Ocean
- Uses Digital Ocean Spaces as Terraform Backend

```
BUCKET_NAME=terraform-state-kubestack-`git rev-parse --short HEAD`
AWS_ACCESS_KEY_ID="{SPACES_ACCESS_KEY}"
AWS_SECRET_ACCESS_KEY="{SPACES_SECRET_KEY}"
AWS_S3_ENDPOINT= "{SPACES_ENDPOINT}"
sed -i 's/bucket = ""/bucket = "'{BUCKET_NAME}'"/g' state.tf
DIGITALOCEAN_TOKEN="{DIGITAL_OCEAN_TOKEN}"
```
> As terraform uses AWS's S3 backend module to store state in, you need to set the same variables. However you will need to create the space before hand (Along with the Access Key) through the [Digital Ocean UI](https://cloud.digitalocean.com/spaces)

# Short falls
As DO Kubernetes is currently in Limited Availability there are some short comings:
- Only available in certain regions
- You can not assign floating IP's to your LoadBalancers

### CODE REVIEW

**Comment by pst** [comment]
For disclosure, @Spazzy757 is a colleague of mine and we discussed this in person. For transparency:

Adding another platform requires a commitment to maintain it over time. Since Kubestack is still in beta, there are a number of expected changes to come that affect multiple platforms - e.g. the recent default ingress controller feature. Each additional platform makes that harder. So far, there has not been demand for DO support.

Because of these reasons, I've decided to not merge this PR for now. I'd like to keep it open, see if there is demand for DO and if so, rebase and merge it.

**Comment by clakeb** [comment]
I'm excited about this. Would love to see this implemented. Maybe take a plugin approach while maintaining what makes sense is the best approach.

**Comment by Spazzy757** [comment]
@pst are you looking at reviving this as I know that @chris-cmsoft was talking to me about it a while ago

**Comment by pst** [comment]
If there's enough community interest I'm open to accept contributions, but contributors need to also take responsibility for future maintenance.

We can also discuss an intermediate mode, where this is maintained as an extension module in its own repository to gauge community interest before it's merged into the main repo.

So first it would be about implementing the `cluster` and `cluster-local` modules that meet Kubestack's module API and using the inheritance and metadata modules internally.

Happy to jump on a call to discuss in more detail. If anyone is interested feel free to reach out and we can set something up.

**Comment by pst** [comment]
At this point this has diverged so far from the code base, I decided to close this PR.

**Pull request closed without merging**
